name: Setup CouchDB
author: Erwan Guyader
description: Starts a CouchDB server of the given version on the given port.
inputs:
  couchdb-version:
    description: 'The version of CouchDB to run'
    required: true
  couchdb-port:
    description: 'The port on which to expose the internal CouchDB port'
    required: false
    default: 5984
  couchdb-user:
    description: 'Username of the admin user'
    required: true
  couchdb-password:
    description: 'Password of the admin user'
    required: true
outputs:
  couchdb-url:
    description: 'The base URL to make requests to CouchDB'
    value: ${{ steps.setup-couchdb.outputs.couchdb-url }}
runs:
  using: composite
  steps:
    - name: Setup podman-machine
      shell: bash
      run: |
        curl -L https://github.com/boot2podman/machine/releases/download/v0.17/podman-machine.darwin-amd64 --output /usr/local/bin/podman-machine
        chmod +x /usr/local/bin/podman-machine
        until [[ $(podman-machine status box) == "Running" ]]
        do
          podman-machine create \
          --virtualbox-boot2podman-url https://github.com/boot2podman/boot2podman-fedora-iso/releases/download/af598af/boot2podman-fedora.iso \
          --virtualbox-hostonly-cidr "192.168.56.1/24" \
          box || true
          sleep 1
        done

    - name: Setup CouchDB
      id: setup-couchdb
      shell: bash
      run: |
        podman-machine ssh box -L ${{ inputs.couchdb-port }}:localhost:5984 -N &

        echo "Downloading CouchDB docker image..."
        _=$(podman-machine ssh box -- sudo podman pull apache/couchdb:${{ inputs.couchdb-version }}) # assign result to var to avoid exiting if the command errors out
        until [[ $? -eq 0 ]]
        do
          echo "Retrying CouchDB docker image download..."
          _=$(podman-machine ssh box -- sudo podman pull apache/couchdb:${{ inputs.couchdb-version }})
        done

        echo "Starting CouchDB..."
        podman-machine ssh box \
          -- sudo podman run -d \
          -p 5984:5984 \
          -e "COUCHDB_USER=${{ inputs.couchdb-user }}" \
          -e "COUCHDB_PASSWORD=${{ inputs.couchdb-password }}" \
          --name couch \
          apache/couchdb:${{ inputs.couchdb-version }}

        echo "Waiting for CouchDB server to be ready..."
        sleep 5

        COUCHDB_URL="http://${{ inputs.couchdb-user }}:${{ inputs.couchdb-password }}@localhost:${{ inputs.couchdb-port }}/"
        echo "couchdb-url=$(echo $COUCHDB_URL)" >> $GITHUB_OUTPUT
